name: Windows-build
on:
  workflow_dispatch:

jobs:
  job:
    runs-on: windows-2022
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.30
        id: cuda-toolkit
        with:
          cuda: '11.8.0'

      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Set CUDA host compiler
        shell: pwsh
        run: |
          $cl = (Get-Command cl.exe).Source
          echo "CUDAHOSTCXX=$cl" >> $env:GITHUB_ENV
          echo "CUDAFLAGS=--use-local-env" >> $env:GITHUB_ENV

      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Run CMake+vcpkg+Ninja+CTest to build packages and generate/build/test the code.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-vcpkg-release'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xenblocksMiner-windows
          path: build/bin
